version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    volumes:
      - ./src:/data
    environment:
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-phper}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - LOG_CHANNEL=${LOG_CHANNEL:-stderr}
      - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./src:/data
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:-localhost}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST:-hoge}

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-phper}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}

  cron:
    build:
      context: .
      dockerfile: ./docker/cron/Dockerfile
      # target: ${APP_BUILD_TARGET:-development}
      target: ${APP_BUILD_TARGET:-deployment}
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-phper}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      - DROPBOX_APP_KEY=${DROPBOX_APP_KEY:-xxxxxxxxxx}
      - DROPBOX_APP_SECRET=${DROPBOX_APP_SECRET:-xxxxxxxxxx}
      - DROPBOX_REFRESH_TOKEN=${DROPBOX_REFRESH_TOKEN:-xxxxxxxxxx}

volumes:
  db-store:

networks:
  default:
    external: true
    name: proxy_network
